imalive updates

diff --git a/rootfs/etc/s6-overlay/scripts/imalive b/rootfs/etc/s6-overlay/scripts/imalive
--- a/rootfs/etc/s6-overlay/scripts/imalive
+++ b/rootfs/etc/s6-overlay/scripts/imalive
@@ -41,7 +41,7 @@ do
     st=${FEEDER_KEY%%:*}
     timestamp=$(date "+%s")
     #echo " $st Current Time : $ts"
-    STATUS="$(curl -sSL "${RV_SERVER%%:*}"/rtools/pyalive.php?stid="${st,,}")"
+    STATUS="$(curl -sSL "${RV_SERVER%%:*}"/rtools/pyalive.php?stid="${st,,}" 2>&1)" || true
     # STATUS now contains either "ok-12345678" or "ko-12345678"
     # where ok/ko means OK or not OK and 12345678 is the secs since epoch
     # STATUS can also contain the error page if the server returns an error
@@ -70,9 +70,12 @@ do
         "${s6wrap[@]}" echo "ImAlive Server says that no data is received: Restarting ANfeeder"
         killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="no data received by server failure"
-        # /usr/bin/RestartANfeeder.sh;
+    elif [[ "$status" == "ok" ]]; then
+        chk_enabled "${VERBOSE}" && "${s6wrap[@]}" echo "ImAlive Server: connection is fine!"
     else
-        chk_enabled "${VERBOSE}" && "${s6wrap[@]}" echo "ImAlive Server: connection is fine!" || true
+        "${s6wrap[@]}" echo "ImAlife error: $STATUS. Restarting ANfeeder"
+        killall /home/py/ANfeeder >/dev/null 2>&1
+        ALIVE="$STATUS"
     fi
 
     # check the SOURCE_HOST connection
