updates to ImAlive checking mechanism

diff --git a/rootfs/etc/services.d/imalive/run b/rootfs/etc/services.d/imalive/run
--- a/rootfs/etc/services.d/imalive/run
+++ b/rootfs/etc/services.d/imalive/run
@@ -42,36 +42,35 @@ do
     ts=$(date "+%s")
     #echo " $st Current Time : $ts"
     STATUS=$(curl -s http://mg2.adsbnetwork.com:/rtools/pyalive.php?stid=$st);
-
     status="${STATUS%%-*}"
     rts="${STATUS##*-}"
     rts=$((rts-10));
 
     # check the ImAlive server:
-    if [[ "$(echo $STATUS | grep -o "404")" == "404" ]]
+    if grep -o "404 Not Found" <<< "$STATUS" >/dev/null 2>&1;
     then
         echo  "[$APPNAME][$(date)] Server returned 404-Not Found at $ts. Restarting ANFeeder \"just in case\"..."
-        killall /home/py/ANfeeder
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="404 failure"
     elif [[ -z  $STATUS ]]
     then
         echo  "[$APPNAME][$(date)] No Network at $ts. Restarting ANFeeder \"just in case\"..."
-        killall /home/py/ANfeeder
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="no network failure"
     elif [[ $ts -lt $rts ]]
     then
         # kx1t: using s6 to restart the service instead of the RestartANfeeder.sh script
         echo "[$APPNAME][$(date)] Time stamp discrepancy: Restart ANfeeder at date $ts "
         # kx1t: added warning that Docker image cannot resync NTP
-        echo "[$APPNAME][$(date)] Warning - Feeder script would like to resync NTP, but this cannot done from without a Docker container."
-        killall /home/py/ANfeeder
+        echo "[$APPNAME][$(date)] Warning - Feeder script would like to resync NTP, but this cannot done from within a Docker container."
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="time discrepancy failure"
         # /usr/bin/RestartANfeeder.sh majdate;
     elif [[ "$status" == "ko" ]]
     then
         # kx1t: using s6 to restart the service
         echo "[$APPNAME][$(date)] Server says that no data is received: Restart ANfeeder at date $ts "
-        killall /home/py/ANfeeder
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="no data received by server failure"
         # /usr/bin/RestartANfeeder.sh;
     else
@@ -79,21 +78,26 @@ do
     fi
 
     # check the SOURCE_HOST connection
-    if ! check_tcp4_connection_established ANY ANY $(get_ipv4 ${SOURCE_HOST%%:*}) ${SOURCE_HOST##*:} >/dev/null 2>&1
+    # if ! check_tcp4_connection_established ANY ANY $(get_ipv4 ${SOURCE_HOST%%:*}) ${SOURCE_HOST##*:} >/dev/null 2>&1
+    if [[ $(timeout --preserve-status 10 netcat -z -v ${SOURCE_HOST%%:*} ${SOURCE_HOST##*:} 2>/dev/null ; echo $?) != "0" ]]
     then
         echo "[$APPNAME][$(date)] You data source at $SOURCE_HOST appears to be down. Restarting ANfeeder at date $ts"
-        killall /home/py/ANfeeder
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="cannot establish connection to SOURCE HOST $SOURCE_HOST"
     else
         [[ "$VERBOSE" == "ON" ]] && echo "[$APPNAME][$(date)] $SOURCE_HOST can be reached! "
     fi
 
-
     # check if the RV_SERVER can be reached
-    if ! check_udp4_connection_established ANY ANY $(get_ipv4 ${RV_SERVER%%:*}) ${RV_SERVER##*:} >/dev/null 2>&1
+    # Note - in the future we have to revisit this. `netcat -u` relies on ICMP Not Available messages from a UDP port to be
+    # returned in case of failure, and often these messages are not sent or are filtered on the way back.
+    # See https://serverfault.com/a/416269 for explanation
+    #
+    # if ! check_udp4_connection_established ANY ANY $(get_ipv4 ${RV_SERVER%%:*}) ${RV_SERVER##*:} >/dev/null 2>&1
+    if [[ $(timeout --preserve-status 10 netcat -u -z -v ${RV_SERVER%%:*} ${RV_SERVER##*:} 2>/dev/null ; echo $?) != "0" ]]
     then
         echo "[$APPNAME][$(date)] The RadarVirtuel server at $RV_SERVER appears to be down. Restarting ANfeeder at date $ts"
-        killall /home/py/ANfeeder
+        killall /home/py/ANfeeder >/dev/null 2>&1
         ALIVE="$RV_SERVER down failure"
     else
         [[ "$VERBOSE" == "ON" ]] && echo "[$APPNAME][$(date)] $RV_SERVER can be reached! "
